spring.application.name=entrega2
#Hace la conexion, con MySQl, referenciando al puerto por defecto.
spring.datasource.url=jdbc:mysql://localhost:3306/entrega2
#Si tiene otra data base, cambie el root por el nombre de la misma
spring.datasource.username=root
#Esto es por que estamos aprendiendo, pero la clave que yo puse a mi local es admin.
spring.datasource.password=papasdelimon
# Generalidad por defecto que conecta que es como el driver para red MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate gestiona el esquema:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
