package com.proyecto.entrega2.entity;

public enum possiblePlatforms {
    PC, PLAYSTATION, XBOX, NINTENDO_SWITCH, NINTENDO_3DS, WII, WII_U, GAMECUBE, NINTENDO_64,SUPER_NINTENDO, NES, SEGA_GENESIS, SEGA_SATURN, DREAMCAST,PLAYSTATION_2, PLAYSTATION_3, PLAYSTATION_4, PLAYSTATION_5, XBOX_360, XBOX_ONE,XBOX_SERIES_X, XBOX_SERIES_S, ANDROID, IOS, TABLET, MAC, LINUX, STEAM_DECK, OCULUS_QUEST, META_QUEST, PLAYSTATION_VR, HTC_VIVE, PICO, NINTENDO_DS, GAME_BOY, GAME_BOY_ADVANCE, PSP, PS_VITA, ARCADE, SMART_TV, WEB, CLOUD_GAMING, AMAZON_LUNA, NVIDIA_GEFORCE_NOW, GOOGLE_STADIA;
    public String getDisplayName() {
        return this.name().replace("_", " ");
    }
    }
